<?php

namespace Tests\Feature;

use App\Jobs\SendSmsJob;
use App\Models\Customer;
use App\Models\GeneralSetting;
use App\Models\SmsGateway;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Queue;
use Tests\TestCase;

class SmsTriggerFeaturesTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();

        GeneralSetting::create([
            'name' => 'MondolShopBD',
            'status' => 1,
        ]);
    }

    public function test_forgot_password_verify_dispatches_otp_sms_when_enabled(): void
    {
        Queue::fake([SendSmsJob::class]);

        SmsGateway::create([
            'provider' => 'joypurhost',
            'url' => 'https://sms.joypurhost.com/api/smsapi',
            'api_key' => 'secret_key',
            'sender_id' => '8809612000000',
            'status' => 1,
            'forget_pass' => 1,
            'password_g' => 0,
        ]);

        $customer = Customer::create([
            'name' => 'Rafi Ahmed',
            'slug' => 'rafi-ahmed-1',
            'phone' => '01711223344',
            'password' => bcrypt('password123'),
            'verify' => 1,
            'status' => 1,
        ]);

        $response = $this->post(route('customer.forgot.verify'), [
            'phone' => '01711223344',
        ]);

        $response->assertRedirect(route('customer.forgot.reset'));

        Queue::assertPushed(SendSmsJob::class, function ($job) use ($customer) {
            $customer->refresh();
            return $job->phone === '01711223344'
                && str_contains($job->message, 'password reset OTP is: ' . $customer->forgot)
                && str_contains($job->message, 'MondolShopBD');
        });
    }

    public function test_forgot_password_verify_does_not_dispatch_sms_when_toggle_is_disabled(): void
    {
        Queue::fake([SendSmsJob::class]);

        SmsGateway::create([
            'provider' => 'joypurhost',
            'status' => 1,
            'forget_pass' => 0, // Disabled
            'password_g' => 0,
        ]);

        Customer::create([
            'name' => 'Rafi Ahmed',
            'slug' => 'rafi-ahmed-2',
            'phone' => '01711223344',
            'password' => bcrypt('password123'),
            'verify' => 1,
            'status' => 1,
        ]);

        $response = $this->post(route('customer.forgot.verify'), [
            'phone' => '01711223344',
        ]);

        $response->assertRedirect(route('customer.forgot.reset'));

        Queue::assertNothingPushed();
    }

    public function test_forgot_password_resend_dispatches_otp_sms_when_enabled(): void
    {
        Queue::fake([SendSmsJob::class]);

        SmsGateway::create([
            'provider' => 'joypurhost',
            'status' => 1,
            'forget_pass' => 1,
        ]);

        $customer = Customer::create([
            'name' => 'Rafi Ahmed',
            'slug' => 'rafi-ahmed-3',
            'phone' => '01711223344',
            'password' => bcrypt('password123'),
            'verify' => 1,
            'status' => 1,
        ]);

        $response = $this->withSession(['verify_phone' => '01711223344'])
            ->post(route('customer.forgot.resendotp'));

        $response->assertRedirect();

        Queue::assertPushed(SendSmsJob::class, function ($job) use ($customer) {
            $customer->refresh();
            return $job->phone === '01711223344'
                && str_contains($job->message, (string) $customer->forgot);
        });
    }

    public function test_auto_generated_password_sms_dispatches_when_password_g_is_enabled(): void
    {
        Queue::fake([SendSmsJob::class]);

        SmsGateway::create([
            'provider' => 'joypurhost',
            'status' => 1,
            'password_g' => 1,
        ]);

        $customer = Customer::create([
            'name' => 'Guest Buyer',
            'slug' => 'guest-buyer-1',
            'phone' => '01811998877',
            'password' => bcrypt('987654'),
            'verify' => 1,
            'status' => 1,
        ]);

        $dispatched = SmsGateway::sendAutoGeneratedPasswordSms($customer, '987654');

        $this->assertTrue($dispatched);

        Queue::assertPushed(SendSmsJob::class, function ($job) use ($customer) {
            return $job->phone === '01811998877'
                && str_contains($job->message, 'Username: 01811998877')
                && str_contains($job->message, 'Password: 987654')
                && str_contains($job->message, 'MondolShopBD');
        });
    }

    public function test_auto_generated_password_sms_does_not_dispatch_when_disabled(): void
    {
        Queue::fake([SendSmsJob::class]);

        SmsGateway::create([
            'provider' => 'joypurhost',
            'status' => 1,
            'password_g' => 0, // Disabled
        ]);

        $customer = Customer::create([
            'name' => 'Guest Buyer',
            'slug' => 'guest-buyer-2',
            'phone' => '01811998877',
            'password' => bcrypt('987654'),
            'verify' => 1,
            'status' => 1,
        ]);

        $dispatched = SmsGateway::sendAutoGeneratedPasswordSms($customer, '987654');

        $this->assertFalse($dispatched);

        Queue::assertNothingPushed();
    }
}
