<?php

namespace App\Models;

use App\Jobs\SendSmsJob;
use App\Models\Customer;
use App\Models\GeneralSetting;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SmsGateway extends Model
{
    public static function getSenderIdColumnName(): string
    {
        try {
            if (\Illuminate\Support\Facades\Schema::hasColumn('sms_gateways', 'sender_id')) {
                return 'sender_id';
            }
        } catch (\Throwable $e) {
            // fallback
        }

        return 'serderid';
    }

    public function getSenderIdAttribute()
    {
        return $this->attributes['sender_id'] ?? $this->attributes['serderid'] ?? null;
    }

    public function setSenderIdAttribute($value)
    {
        $col = static::getSenderIdColumnName();
        $this->attributes[$col] = $value;
        if ($col === 'sender_id') {
            unset($this->attributes['serderid']);
        } else {
            unset($this->attributes['sender_id']);
        }
    }

    public function getSerderidAttribute()
    {
        return $this->getSenderIdAttribute();
    }

    public function setSerderidAttribute($value)
    {
        $this->setSenderIdAttribute($value);
    }

    public const PROVIDER_JOYPURHOST = 'joypurhost';
    public const PROVIDER_CUSTOM = 'custom';

    public static function getAvailableProviders(): array
    {
        return [
            self::PROVIDER_JOYPURHOST => 'JoypurHost SMS',
            self::PROVIDER_CUSTOM => 'Custom Provider',
        ];
    }

    public static function joypurhost(): SmsProviderJoypurhost
    {
        return SmsProviderJoypurhost::getOrCreate();
    }

    public static function custom(): self
    {
        $senderColumn = static::getSenderIdColumnName();
        $defaults = [
            'url' => '',
            'api_key' => '',
            'status' => 0,
            'order' => 0,
            'forget_pass' => 0,
            'password_g' => 0,
        ];
        $defaults[$senderColumn] = '';

        return static::firstOrCreate(
            ['provider' => self::PROVIDER_CUSTOM],
            $defaults
        );
    }

    public static function getActive(): ?self
    {
        return static::where('status', 1)->orWhere('status', '1')->first();
    }

    /**
     * Parse multiple comma- or space-separated admin phone numbers.
     *
     * @return array<int, string>
     */
    public function getAdminPhoneNumbers(): array
    {
        $raw = (string) ($this->admin_phone ?? '');
        if (trim($raw) === '') {
            return [];
        }

        $parts = preg_split('/[,;\r\n]+/', $raw, -1, PREG_SPLIT_NO_EMPTY);
        $cleanNumbers = [];

        foreach ($parts as $part) {
            $num = trim($part);
            if ($num !== '' && !in_array($num, $cleanNumbers, true)) {
                $cleanNumbers[] = $num;
            }
        }

        return $cleanNumbers;
    }

    /**
     * Dispatch password reset OTP SMS if forget_pass toggle and master status are enabled.
     */
    public static function sendPasswordResetOtpSms(Customer $customer, int|string $otp): bool
    {
        $gateway = static::getActive() ?? static::where('status', 1)->first();
        if (!$gateway || (int) $gateway->status !== 1 || (int) $gateway->forget_pass !== 1) {
            return false;
        }

        if (empty($customer->phone)) {
            return false;
        }

        $siteSetting = GeneralSetting::where('status', 1)->first();
        $siteName = $siteSetting ? $siteSetting->name : config('app.name', 'MondolShopBD');
        $customerName = $customer->name ?: 'Customer';
        $message = "Dear {$customerName},\r\nYour password reset OTP is: {$otp}. Valid for 5 minutes. Thank you for using {$siteName}.";

        SendSmsJob::dispatch($customer->phone, $message);
        return true;
    }

    /**
     * Dispatch auto-generated login credentials SMS if password_g toggle and master status are enabled.
     */
    public static function sendAutoGeneratedPasswordSms(Customer $customer, string $plainPassword): bool
    {
        $gateway = static::getActive() ?? static::where('status', 1)->first();
        if (!$gateway || (int) $gateway->status !== 1 || (int) $gateway->password_g !== 1) {
            return false;
        }

        if (empty($customer->phone)) {
            return false;
        }

        $siteSetting = GeneralSetting::where('status', 1)->first();
        $siteName = $siteSetting ? $siteSetting->name : config('app.name', 'MondolShopBD');
        $message = "Welcome to {$siteName}! Your account has been created.\r\nUsername: {$customer->phone}\r\nPassword: {$plainPassword}\r\nPlease login to track your orders.";

        SendSmsJob::dispatch($customer->phone, $message);
        return true;
    }

    /**
     * Dispatch account verification OTP SMS if master status is enabled.
     */
    public static function sendAccountVerificationOtpSms(Customer $customer, int|string $otp): bool
    {
        $gateway = static::getActive() ?? static::where('status', 1)->first();
        if (!$gateway || (int) $gateway->status !== 1) {
            return false;
        }

        if (empty($customer->phone)) {
            return false;
        }

        $siteSetting = GeneralSetting::where('status', 1)->first();
        $siteName = $siteSetting ? $siteSetting->name : config('app.name', 'MondolShopBD');
        $customerName = $customer->name ?: 'Customer';
        $message = "Dear {$customerName},\r\nYour account verification OTP is: {$otp}. Thank you for using {$siteName}.";

        SendSmsJob::dispatch($customer->phone, $message);
        return true;
    }

    use HasFactory;

    protected $fillable = [
        'provider',
        'url',
        'api_key',
        'sender_id',
        'serderid',
        'type',
        'status',
        'order',
        'forget_pass',
        'password_g',
        'admin_phone',
    ];

    protected $casts = [
        'status' => 'integer',
        'order' => 'integer',
        'forget_pass' => 'integer',
        'password_g' => 'integer',
    ];
}
